//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEBESTIBLE
    {
        public BEBESTIBLE()
        {
            this.ORDEN = new HashSet<ORDEN>();
            this.PREPARACION = new HashSet<PREPARACION>();
        }
    
        public decimal ID_BEBESTIBLE { get; set; }
        public string TIPO_BEBESTIBLE { get; set; }
        public decimal PRECIO { get; set; }
        public decimal CANTIDAD_BEBESTIBLE { get; set; }
    
        public virtual ICollection<ORDEN> ORDEN { get; set; }
        public virtual ICollection<PREPARACION> PREPARACION { get; set; }
    }
}
