//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_F
    {
        public decimal CANTIDAD_PEDIDO { get; set; }
        public decimal PRECIO_UNITARIO { get; set; }
        public decimal PRODUCTO_ID_PRODUCTO { get; set; }
        public decimal PRODUCTO_UNIDAD_MEDIDA_ID_M { get; set; }
        public decimal FACTURA_PROV_ID_PROVEEDOR { get; set; }
        public decimal FACTURA_PROVEEDOR_ID_FACTURA { get; set; }
    
        public virtual FACTURA_PROVEEDOR FACTURA_PROVEEDOR { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
