//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_PROVEEDOR
    {
        public FACTURA_PROVEEDOR()
        {
            this.DETALLE_F = new HashSet<DETALLE_F>();
        }
    
        public decimal ID_FACTURA { get; set; }
        public System.DateTime FECHA_PEDIDO { get; set; }
        public string PROVEEDOR_RUT_PROVEEDOR { get; set; }
    
        public virtual ICollection<DETALLE_F> DETALLE_F { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
