//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class METODO_PAGO
    {
        public decimal ID_METODO_PAGO { get; set; }
        public string TIPO_PAGO { get; set; }
        public decimal NRO_CLIENTES { get; set; }
        public decimal BOLETA_ID_BOLETA { get; set; }
        public decimal BOLETA_ID_MESA { get; set; }
    
        public virtual BOLETA BOLETA { get; set; }
    }
}
