//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BEBESTIBLE> BEBESTIBLE { get; set; }
        public DbSet<BOLETA> BOLETA { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<DETALLE_F> DETALLE_F { get; set; }
        public DbSet<FACTURA_PROVEEDOR> FACTURA_PROVEEDOR { get; set; }
        public DbSet<MESA> MESA { get; set; }
        public DbSet<METODO_PAGO> METODO_PAGO { get; set; }
        public DbSet<ORDEN> ORDEN { get; set; }
        public DbSet<PEDIDO> PEDIDO { get; set; }
        public DbSet<PLATO> PLATO { get; set; }
        public DbSet<PREP_BEBESTIBLE> PREP_BEBESTIBLE { get; set; }
        public DbSet<PREP_PLATO> PREP_PLATO { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<UNIDAD_MEDIDA> UNIDAD_MEDIDA { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual int AGREGARCLIENTE(string rUT, string nOMBRES, string aPELLIDO, string cORREOS, string dIRECCIONES, string cLAVES, string aCTIVO)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var nOMBRESParameter = nOMBRES != null ?
                new ObjectParameter("NOMBRES", nOMBRES) :
                new ObjectParameter("NOMBRES", typeof(string));
    
            var aPELLIDOParameter = aPELLIDO != null ?
                new ObjectParameter("APELLIDO", aPELLIDO) :
                new ObjectParameter("APELLIDO", typeof(string));
    
            var cORREOSParameter = cORREOS != null ?
                new ObjectParameter("CORREOS", cORREOS) :
                new ObjectParameter("CORREOS", typeof(string));
    
            var dIRECCIONESParameter = dIRECCIONES != null ?
                new ObjectParameter("DIRECCIONES", dIRECCIONES) :
                new ObjectParameter("DIRECCIONES", typeof(string));
    
            var cLAVESParameter = cLAVES != null ?
                new ObjectParameter("CLAVES", cLAVES) :
                new ObjectParameter("CLAVES", typeof(string));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGARCLIENTE", rUTParameter, nOMBRESParameter, aPELLIDOParameter, cORREOSParameter, dIRECCIONESParameter, cLAVESParameter, aCTIVOParameter);
        }
    
        public virtual int AGREGARMESA(Nullable<decimal> nUMASIENTO, string eSTADOMESA, string uSERRUT, Nullable<decimal> uSERIDROL, string aCTIVO)
        {
            var nUMASIENTOParameter = nUMASIENTO.HasValue ?
                new ObjectParameter("NUMASIENTO", nUMASIENTO) :
                new ObjectParameter("NUMASIENTO", typeof(decimal));
    
            var eSTADOMESAParameter = eSTADOMESA != null ?
                new ObjectParameter("ESTADOMESA", eSTADOMESA) :
                new ObjectParameter("ESTADOMESA", typeof(string));
    
            var uSERRUTParameter = uSERRUT != null ?
                new ObjectParameter("USERRUT", uSERRUT) :
                new ObjectParameter("USERRUT", typeof(string));
    
            var uSERIDROLParameter = uSERIDROL.HasValue ?
                new ObjectParameter("USERIDROL", uSERIDROL) :
                new ObjectParameter("USERIDROL", typeof(decimal));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGARMESA", nUMASIENTOParameter, eSTADOMESAParameter, uSERRUTParameter, uSERIDROLParameter, aCTIVOParameter);
        }
    
        public virtual int AGREGARMETODOPAGO(Nullable<decimal> nUMPAGO, string tIPOPAGO, Nullable<decimal> bOLETAID, string aCTIVO)
        {
            var nUMPAGOParameter = nUMPAGO.HasValue ?
                new ObjectParameter("NUMPAGO", nUMPAGO) :
                new ObjectParameter("NUMPAGO", typeof(decimal));
    
            var tIPOPAGOParameter = tIPOPAGO != null ?
                new ObjectParameter("TIPOPAGO", tIPOPAGO) :
                new ObjectParameter("TIPOPAGO", typeof(string));
    
            var bOLETAIDParameter = bOLETAID.HasValue ?
                new ObjectParameter("BOLETAID", bOLETAID) :
                new ObjectParameter("BOLETAID", typeof(decimal));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGARMETODOPAGO", nUMPAGOParameter, tIPOPAGOParameter, bOLETAIDParameter, aCTIVOParameter);
        }
    
        public virtual int AGREGARPRODUCTO(Nullable<decimal> iDPRODUCTO, Nullable<decimal> sTOCK, string tIPOPRODUCTO, Nullable<decimal> uNIDADMEDIDAID, string aCTIVO)
        {
            var iDPRODUCTOParameter = iDPRODUCTO.HasValue ?
                new ObjectParameter("IDPRODUCTO", iDPRODUCTO) :
                new ObjectParameter("IDPRODUCTO", typeof(decimal));
    
            var sTOCKParameter = sTOCK.HasValue ?
                new ObjectParameter("STOCK", sTOCK) :
                new ObjectParameter("STOCK", typeof(decimal));
    
            var tIPOPRODUCTOParameter = tIPOPRODUCTO != null ?
                new ObjectParameter("TIPOPRODUCTO", tIPOPRODUCTO) :
                new ObjectParameter("TIPOPRODUCTO", typeof(string));
    
            var uNIDADMEDIDAIDParameter = uNIDADMEDIDAID.HasValue ?
                new ObjectParameter("UNIDADMEDIDAID", uNIDADMEDIDAID) :
                new ObjectParameter("UNIDADMEDIDAID", typeof(decimal));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGARPRODUCTO", iDPRODUCTOParameter, sTOCKParameter, tIPOPRODUCTOParameter, uNIDADMEDIDAIDParameter, aCTIVOParameter);
        }
    
        public virtual int AGREGARPROVEEDOR(Nullable<decimal> iDPROVEEDOR, string tIPOPROVEEDOR, string nOMBRES, string rUT, string aPELLIDO, string fONO, string dIRECCION, string aCTIVO)
        {
            var iDPROVEEDORParameter = iDPROVEEDOR.HasValue ?
                new ObjectParameter("IDPROVEEDOR", iDPROVEEDOR) :
                new ObjectParameter("IDPROVEEDOR", typeof(decimal));
    
            var tIPOPROVEEDORParameter = tIPOPROVEEDOR != null ?
                new ObjectParameter("TIPOPROVEEDOR", tIPOPROVEEDOR) :
                new ObjectParameter("TIPOPROVEEDOR", typeof(string));
    
            var nOMBRESParameter = nOMBRES != null ?
                new ObjectParameter("NOMBRES", nOMBRES) :
                new ObjectParameter("NOMBRES", typeof(string));
    
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var aPELLIDOParameter = aPELLIDO != null ?
                new ObjectParameter("APELLIDO", aPELLIDO) :
                new ObjectParameter("APELLIDO", typeof(string));
    
            var fONOParameter = fONO != null ?
                new ObjectParameter("FONO", fONO) :
                new ObjectParameter("FONO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGARPROVEEDOR", iDPROVEEDORParameter, tIPOPROVEEDORParameter, nOMBRESParameter, rUTParameter, aPELLIDOParameter, fONOParameter, dIRECCIONParameter, aCTIVOParameter);
        }
    
        public virtual int AGREGARRESERVA(Nullable<System.DateTime> hORALLEGADA, Nullable<System.DateTime> hORASALIDA, string eSTADORESERVA, Nullable<decimal> cLIENTEID, string aCTIVO)
        {
            var hORALLEGADAParameter = hORALLEGADA.HasValue ?
                new ObjectParameter("HORALLEGADA", hORALLEGADA) :
                new ObjectParameter("HORALLEGADA", typeof(System.DateTime));
    
            var hORASALIDAParameter = hORASALIDA.HasValue ?
                new ObjectParameter("HORASALIDA", hORASALIDA) :
                new ObjectParameter("HORASALIDA", typeof(System.DateTime));
    
            var eSTADORESERVAParameter = eSTADORESERVA != null ?
                new ObjectParameter("ESTADORESERVA", eSTADORESERVA) :
                new ObjectParameter("ESTADORESERVA", typeof(string));
    
            var cLIENTEIDParameter = cLIENTEID.HasValue ?
                new ObjectParameter("CLIENTEID", cLIENTEID) :
                new ObjectParameter("CLIENTEID", typeof(decimal));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGARRESERVA", hORALLEGADAParameter, hORASALIDAParameter, eSTADORESERVAParameter, cLIENTEIDParameter, aCTIVOParameter);
        }
    
        public virtual int AGREGARROL(Nullable<decimal> iDROL, string tIPOROL, string aCTIVO)
        {
            var iDROLParameter = iDROL.HasValue ?
                new ObjectParameter("IDROL", iDROL) :
                new ObjectParameter("IDROL", typeof(decimal));
    
            var tIPOROLParameter = tIPOROL != null ?
                new ObjectParameter("TIPOROL", tIPOROL) :
                new ObjectParameter("TIPOROL", typeof(string));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGARROL", iDROLParameter, tIPOROLParameter, aCTIVOParameter);
        }
    
        public virtual int AGREGARUNIDADMEDIDA(Nullable<decimal> iDUNIDAD, string dESCRIPCION, string aCTIVO)
        {
            var iDUNIDADParameter = iDUNIDAD.HasValue ?
                new ObjectParameter("IDUNIDAD", iDUNIDAD) :
                new ObjectParameter("IDUNIDAD", typeof(decimal));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGARUNIDADMEDIDA", iDUNIDADParameter, dESCRIPCIONParameter, aCTIVOParameter);
        }
    
        public virtual int AGREGARUSUARIO(string rUT, string nOMBRES, string aPELLIDOP, string aPELLIDOM, Nullable<decimal> rOLIDROL, string cORREOS, string dIRECCIONES, string cLAVES, string aCTIVO)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var nOMBRESParameter = nOMBRES != null ?
                new ObjectParameter("NOMBRES", nOMBRES) :
                new ObjectParameter("NOMBRES", typeof(string));
    
            var aPELLIDOPParameter = aPELLIDOP != null ?
                new ObjectParameter("APELLIDOP", aPELLIDOP) :
                new ObjectParameter("APELLIDOP", typeof(string));
    
            var aPELLIDOMParameter = aPELLIDOM != null ?
                new ObjectParameter("APELLIDOM", aPELLIDOM) :
                new ObjectParameter("APELLIDOM", typeof(string));
    
            var rOLIDROLParameter = rOLIDROL.HasValue ?
                new ObjectParameter("ROLIDROL", rOLIDROL) :
                new ObjectParameter("ROLIDROL", typeof(decimal));
    
            var cORREOSParameter = cORREOS != null ?
                new ObjectParameter("CORREOS", cORREOS) :
                new ObjectParameter("CORREOS", typeof(string));
    
            var dIRECCIONESParameter = dIRECCIONES != null ?
                new ObjectParameter("DIRECCIONES", dIRECCIONES) :
                new ObjectParameter("DIRECCIONES", typeof(string));
    
            var cLAVESParameter = cLAVES != null ?
                new ObjectParameter("CLAVES", cLAVES) :
                new ObjectParameter("CLAVES", typeof(string));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGARUSUARIO", rUTParameter, nOMBRESParameter, aPELLIDOPParameter, aPELLIDOMParameter, rOLIDROLParameter, cORREOSParameter, dIRECCIONESParameter, cLAVESParameter, aCTIVOParameter);
        }
    
        public virtual int ELIMINARCLIENTE(Nullable<decimal> iDCLIENTE)
        {
            var iDCLIENTEParameter = iDCLIENTE.HasValue ?
                new ObjectParameter("IDCLIENTE", iDCLIENTE) :
                new ObjectParameter("IDCLIENTE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARCLIENTE", iDCLIENTEParameter);
        }
    
        public virtual int ELIMINARMESA(Nullable<decimal> iDMESA)
        {
            var iDMESAParameter = iDMESA.HasValue ?
                new ObjectParameter("IDMESA", iDMESA) :
                new ObjectParameter("IDMESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARMESA", iDMESAParameter);
        }
    
        public virtual int ELIMINARMETODOPAGO(Nullable<decimal> nUMPAGO)
        {
            var nUMPAGOParameter = nUMPAGO.HasValue ?
                new ObjectParameter("NUMPAGO", nUMPAGO) :
                new ObjectParameter("NUMPAGO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARMETODOPAGO", nUMPAGOParameter);
        }
    
        public virtual int ELIMINARPRODUCTO(Nullable<decimal> iDPRODUCTO)
        {
            var iDPRODUCTOParameter = iDPRODUCTO.HasValue ?
                new ObjectParameter("IDPRODUCTO", iDPRODUCTO) :
                new ObjectParameter("IDPRODUCTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARPRODUCTO", iDPRODUCTOParameter);
        }
    
        public virtual int ELIMINARPROVEEDOR(Nullable<decimal> iDPROVEEDOR)
        {
            var iDPROVEEDORParameter = iDPROVEEDOR.HasValue ?
                new ObjectParameter("IDPROVEEDOR", iDPROVEEDOR) :
                new ObjectParameter("IDPROVEEDOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARPROVEEDOR", iDPROVEEDORParameter);
        }
    
        public virtual int ELIMINARRESERVA(Nullable<decimal> iDRESERVA)
        {
            var iDRESERVAParameter = iDRESERVA.HasValue ?
                new ObjectParameter("IDRESERVA", iDRESERVA) :
                new ObjectParameter("IDRESERVA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARRESERVA", iDRESERVAParameter);
        }
    
        public virtual int ELIMINARROL(Nullable<decimal> iDROL)
        {
            var iDROLParameter = iDROL.HasValue ?
                new ObjectParameter("IDROL", iDROL) :
                new ObjectParameter("IDROL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARROL", iDROLParameter);
        }
    
        public virtual int ELIMINARUNIDADMEDIDA(Nullable<decimal> iDUNIDAD)
        {
            var iDUNIDADParameter = iDUNIDAD.HasValue ?
                new ObjectParameter("IDUNIDAD", iDUNIDAD) :
                new ObjectParameter("IDUNIDAD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARUNIDADMEDIDA", iDUNIDADParameter);
        }
    
        public virtual int ELIMINARUSUARIO(string rUT)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARUSUARIO", rUTParameter);
        }
    
        public virtual int LISTARCLIENTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARCLIENTE");
        }
    
        public virtual int LISTARMESA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARMESA");
        }
    
        public virtual int LISTARMETODOPAGO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARMETODOPAGO");
        }
    
        public virtual int LISTARPRODUCTO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARPRODUCTO");
        }
    
        public virtual int LISTARPROVEEDOR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARPROVEEDOR");
        }
    
        public virtual int LISTARRESERVA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARRESERVA");
        }
    
        public virtual int LISTARROL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARROL");
        }
    
        public virtual int LISTARUNIDADMEDIDA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARUNIDADMEDIDA");
        }
    
        public virtual int LISTARUSUARIO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARUSUARIO");
        }
    
        public virtual int MODIFICARCLIENTE(string rUT, string nOMBRES, string aPELLIDO, string cORREOS, string dIRECCIONES, string cLAVES, string aCTIVO)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var nOMBRESParameter = nOMBRES != null ?
                new ObjectParameter("NOMBRES", nOMBRES) :
                new ObjectParameter("NOMBRES", typeof(string));
    
            var aPELLIDOParameter = aPELLIDO != null ?
                new ObjectParameter("APELLIDO", aPELLIDO) :
                new ObjectParameter("APELLIDO", typeof(string));
    
            var cORREOSParameter = cORREOS != null ?
                new ObjectParameter("CORREOS", cORREOS) :
                new ObjectParameter("CORREOS", typeof(string));
    
            var dIRECCIONESParameter = dIRECCIONES != null ?
                new ObjectParameter("DIRECCIONES", dIRECCIONES) :
                new ObjectParameter("DIRECCIONES", typeof(string));
    
            var cLAVESParameter = cLAVES != null ?
                new ObjectParameter("CLAVES", cLAVES) :
                new ObjectParameter("CLAVES", typeof(string));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARCLIENTE", rUTParameter, nOMBRESParameter, aPELLIDOParameter, cORREOSParameter, dIRECCIONESParameter, cLAVESParameter, aCTIVOParameter);
        }
    
        public virtual int MODIFICARMESA(Nullable<decimal> nUMASIENTO, string eSTADOMESA, string uSERRUT, Nullable<decimal> uSERIDROL, string aCTIVO)
        {
            var nUMASIENTOParameter = nUMASIENTO.HasValue ?
                new ObjectParameter("NUMASIENTO", nUMASIENTO) :
                new ObjectParameter("NUMASIENTO", typeof(decimal));
    
            var eSTADOMESAParameter = eSTADOMESA != null ?
                new ObjectParameter("ESTADOMESA", eSTADOMESA) :
                new ObjectParameter("ESTADOMESA", typeof(string));
    
            var uSERRUTParameter = uSERRUT != null ?
                new ObjectParameter("USERRUT", uSERRUT) :
                new ObjectParameter("USERRUT", typeof(string));
    
            var uSERIDROLParameter = uSERIDROL.HasValue ?
                new ObjectParameter("USERIDROL", uSERIDROL) :
                new ObjectParameter("USERIDROL", typeof(decimal));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARMESA", nUMASIENTOParameter, eSTADOMESAParameter, uSERRUTParameter, uSERIDROLParameter, aCTIVOParameter);
        }
    
        public virtual int MODIFICARMETODOPAGO(Nullable<decimal> nUMPAGO, string tIPOPAGO, Nullable<decimal> bOLETAID, string aCTIVO)
        {
            var nUMPAGOParameter = nUMPAGO.HasValue ?
                new ObjectParameter("NUMPAGO", nUMPAGO) :
                new ObjectParameter("NUMPAGO", typeof(decimal));
    
            var tIPOPAGOParameter = tIPOPAGO != null ?
                new ObjectParameter("TIPOPAGO", tIPOPAGO) :
                new ObjectParameter("TIPOPAGO", typeof(string));
    
            var bOLETAIDParameter = bOLETAID.HasValue ?
                new ObjectParameter("BOLETAID", bOLETAID) :
                new ObjectParameter("BOLETAID", typeof(decimal));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARMETODOPAGO", nUMPAGOParameter, tIPOPAGOParameter, bOLETAIDParameter, aCTIVOParameter);
        }
    
        public virtual int MODIFICARPRODUCTO(Nullable<decimal> iDPRODUCTO, Nullable<decimal> sTOCK, string tIPOPRODUCTO, Nullable<decimal> uNIDADMEDIDAID, string aCTIVO)
        {
            var iDPRODUCTOParameter = iDPRODUCTO.HasValue ?
                new ObjectParameter("IDPRODUCTO", iDPRODUCTO) :
                new ObjectParameter("IDPRODUCTO", typeof(decimal));
    
            var sTOCKParameter = sTOCK.HasValue ?
                new ObjectParameter("STOCK", sTOCK) :
                new ObjectParameter("STOCK", typeof(decimal));
    
            var tIPOPRODUCTOParameter = tIPOPRODUCTO != null ?
                new ObjectParameter("TIPOPRODUCTO", tIPOPRODUCTO) :
                new ObjectParameter("TIPOPRODUCTO", typeof(string));
    
            var uNIDADMEDIDAIDParameter = uNIDADMEDIDAID.HasValue ?
                new ObjectParameter("UNIDADMEDIDAID", uNIDADMEDIDAID) :
                new ObjectParameter("UNIDADMEDIDAID", typeof(decimal));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARPRODUCTO", iDPRODUCTOParameter, sTOCKParameter, tIPOPRODUCTOParameter, uNIDADMEDIDAIDParameter, aCTIVOParameter);
        }
    
        public virtual int MODIFICARPROVEEDOR(Nullable<decimal> iDPROVEEDOR, string tIPOPROVEEDOR, string nOMBRES, string rUT, string aPELLIDO, string fONO, string dIRECCION, string aCTIVO)
        {
            var iDPROVEEDORParameter = iDPROVEEDOR.HasValue ?
                new ObjectParameter("IDPROVEEDOR", iDPROVEEDOR) :
                new ObjectParameter("IDPROVEEDOR", typeof(decimal));
    
            var tIPOPROVEEDORParameter = tIPOPROVEEDOR != null ?
                new ObjectParameter("TIPOPROVEEDOR", tIPOPROVEEDOR) :
                new ObjectParameter("TIPOPROVEEDOR", typeof(string));
    
            var nOMBRESParameter = nOMBRES != null ?
                new ObjectParameter("NOMBRES", nOMBRES) :
                new ObjectParameter("NOMBRES", typeof(string));
    
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var aPELLIDOParameter = aPELLIDO != null ?
                new ObjectParameter("APELLIDO", aPELLIDO) :
                new ObjectParameter("APELLIDO", typeof(string));
    
            var fONOParameter = fONO != null ?
                new ObjectParameter("FONO", fONO) :
                new ObjectParameter("FONO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARPROVEEDOR", iDPROVEEDORParameter, tIPOPROVEEDORParameter, nOMBRESParameter, rUTParameter, aPELLIDOParameter, fONOParameter, dIRECCIONParameter, aCTIVOParameter);
        }
    
        public virtual int MODIFICARRESERVA(Nullable<System.DateTime> hORALLEGADA, Nullable<System.DateTime> hORASALIDA, string eSTADORESERVA, Nullable<decimal> cLIENTEID, string aCTIVO)
        {
            var hORALLEGADAParameter = hORALLEGADA.HasValue ?
                new ObjectParameter("HORALLEGADA", hORALLEGADA) :
                new ObjectParameter("HORALLEGADA", typeof(System.DateTime));
    
            var hORASALIDAParameter = hORASALIDA.HasValue ?
                new ObjectParameter("HORASALIDA", hORASALIDA) :
                new ObjectParameter("HORASALIDA", typeof(System.DateTime));
    
            var eSTADORESERVAParameter = eSTADORESERVA != null ?
                new ObjectParameter("ESTADORESERVA", eSTADORESERVA) :
                new ObjectParameter("ESTADORESERVA", typeof(string));
    
            var cLIENTEIDParameter = cLIENTEID.HasValue ?
                new ObjectParameter("CLIENTEID", cLIENTEID) :
                new ObjectParameter("CLIENTEID", typeof(decimal));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARRESERVA", hORALLEGADAParameter, hORASALIDAParameter, eSTADORESERVAParameter, cLIENTEIDParameter, aCTIVOParameter);
        }
    
        public virtual int MODIFICARROL(Nullable<decimal> iDROL, string tIPOROL, string aCTIVO)
        {
            var iDROLParameter = iDROL.HasValue ?
                new ObjectParameter("IDROL", iDROL) :
                new ObjectParameter("IDROL", typeof(decimal));
    
            var tIPOROLParameter = tIPOROL != null ?
                new ObjectParameter("TIPOROL", tIPOROL) :
                new ObjectParameter("TIPOROL", typeof(string));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARROL", iDROLParameter, tIPOROLParameter, aCTIVOParameter);
        }
    
        public virtual int MODIFICARUNIDADMEDIDA(Nullable<decimal> iDUNIDAD, string dESCRIPCION, string aCTIVO)
        {
            var iDUNIDADParameter = iDUNIDAD.HasValue ?
                new ObjectParameter("IDUNIDAD", iDUNIDAD) :
                new ObjectParameter("IDUNIDAD", typeof(decimal));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARUNIDADMEDIDA", iDUNIDADParameter, dESCRIPCIONParameter, aCTIVOParameter);
        }
    
        public virtual int MODIFICARUSUARIO(string rUT, string nOMBRES, string aPELLIDOP, string aPELLIDOM, Nullable<decimal> rOLIDROL, string cORREOS, string dIRECCIONES, string cLAVES, string aCTIVO)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var nOMBRESParameter = nOMBRES != null ?
                new ObjectParameter("NOMBRES", nOMBRES) :
                new ObjectParameter("NOMBRES", typeof(string));
    
            var aPELLIDOPParameter = aPELLIDOP != null ?
                new ObjectParameter("APELLIDOP", aPELLIDOP) :
                new ObjectParameter("APELLIDOP", typeof(string));
    
            var aPELLIDOMParameter = aPELLIDOM != null ?
                new ObjectParameter("APELLIDOM", aPELLIDOM) :
                new ObjectParameter("APELLIDOM", typeof(string));
    
            var rOLIDROLParameter = rOLIDROL.HasValue ?
                new ObjectParameter("ROLIDROL", rOLIDROL) :
                new ObjectParameter("ROLIDROL", typeof(decimal));
    
            var cORREOSParameter = cORREOS != null ?
                new ObjectParameter("CORREOS", cORREOS) :
                new ObjectParameter("CORREOS", typeof(string));
    
            var dIRECCIONESParameter = dIRECCIONES != null ?
                new ObjectParameter("DIRECCIONES", dIRECCIONES) :
                new ObjectParameter("DIRECCIONES", typeof(string));
    
            var cLAVESParameter = cLAVES != null ?
                new ObjectParameter("CLAVES", cLAVES) :
                new ObjectParameter("CLAVES", typeof(string));
    
            var aCTIVOParameter = aCTIVO != null ?
                new ObjectParameter("ACTIVO", aCTIVO) :
                new ObjectParameter("ACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARUSUARIO", rUTParameter, nOMBRESParameter, aPELLIDOPParameter, aPELLIDOMParameter, rOLIDROLParameter, cORREOSParameter, dIRECCIONESParameter, cLAVESParameter, aCTIVOParameter);
        }
    
        public virtual int AGREGARBOLETA(Nullable<decimal> tOTALPAGAR, Nullable<decimal> mONTOPAGADO, Nullable<System.DateTime> fECHABOLETA, Nullable<decimal> cAMBIO, Nullable<decimal> iDPEDIDO, Nullable<decimal> iDMESA)
        {
            var tOTALPAGARParameter = tOTALPAGAR.HasValue ?
                new ObjectParameter("TOTALPAGAR", tOTALPAGAR) :
                new ObjectParameter("TOTALPAGAR", typeof(decimal));
    
            var mONTOPAGADOParameter = mONTOPAGADO.HasValue ?
                new ObjectParameter("MONTOPAGADO", mONTOPAGADO) :
                new ObjectParameter("MONTOPAGADO", typeof(decimal));
    
            var fECHABOLETAParameter = fECHABOLETA.HasValue ?
                new ObjectParameter("FECHABOLETA", fECHABOLETA) :
                new ObjectParameter("FECHABOLETA", typeof(System.DateTime));
    
            var cAMBIOParameter = cAMBIO.HasValue ?
                new ObjectParameter("CAMBIO", cAMBIO) :
                new ObjectParameter("CAMBIO", typeof(decimal));
    
            var iDPEDIDOParameter = iDPEDIDO.HasValue ?
                new ObjectParameter("IDPEDIDO", iDPEDIDO) :
                new ObjectParameter("IDPEDIDO", typeof(decimal));
    
            var iDMESAParameter = iDMESA.HasValue ?
                new ObjectParameter("IDMESA", iDMESA) :
                new ObjectParameter("IDMESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGARBOLETA", tOTALPAGARParameter, mONTOPAGADOParameter, fECHABOLETAParameter, cAMBIOParameter, iDPEDIDOParameter, iDMESAParameter);
        }
    
        public virtual int DETALLEORDEN(Nullable<decimal> iD_MESA)
        {
            var iD_MESAParameter = iD_MESA.HasValue ?
                new ObjectParameter("ID_MESA", iD_MESA) :
                new ObjectParameter("ID_MESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DETALLEORDEN", iD_MESAParameter);
        }
    }
}
