//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN
    {
        public ORDEN()
        {
            this.BEBESTIBLE = new HashSet<BEBESTIBLE>();
            this.PLATO = new HashSet<PLATO>();
        }
    
        public decimal NRO_ORDEN { get; set; }
        public decimal CANTIDAD_PLATO { get; set; }
        public decimal PEDIDO_ID_PEDIDO { get; set; }
        public decimal CANTIDAD_BEBESTIBLE { get; set; }
        public decimal PEDIDO_MESA_ID_MESA { get; set; }
    
        public virtual ICollection<BEBESTIBLE> BEBESTIBLE { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual ICollection<PLATO> PLATO { get; set; }
    }
}
