//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN
    {
        public decimal CANTIDAD_PLATO { get; set; }
        public decimal PLATO_ID_PLATO { get; set; }
        public decimal PEDIDO_ID_PEDIDO { get; set; }
        public decimal BEBESTIBLE_ID_BEBESTIBLE { get; set; }
        public decimal CANTIDAD_BEBESTIBLE { get; set; }
    
        public virtual BEBESTIBLE BEBESTIBLE { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual PLATO PLATO { get; set; }
    }
}
