//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public PEDIDO()
        {
            this.BOLETA = new HashSet<BOLETA>();
            this.ORDEN = new HashSet<ORDEN>();
        }
    
        public decimal ID_PEDIDO { get; set; }
        public string ESTADO_PEDIDO { get; set; }
        public string TIPO_PEDIDO { get; set; }
        public decimal MESA_ID_MESA { get; set; }
    
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual MESA MESA { get; set; }
        public virtual ICollection<ORDEN> ORDEN { get; set; }
    }
}
