//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public PEDIDO()
        {
            this.ORDEN = new HashSet<ORDEN>();
            this.MESA = new HashSet<MESA>();
        }
    
        public decimal ID_PEDIDO { get; set; }
        public string ESATADO_PEDIDO { get; set; }
        public System.DateTime TIEMPO { get; set; }
        public string TIPO_PEDIDO { get; set; }
        public string USUARIO_RUT { get; set; }
        public decimal USUARIO_ROL_ID_ROL { get; set; }
    
        public virtual ICollection<ORDEN> ORDEN { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<MESA> MESA { get; set; }
    }
}
