//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.FACTURA_COMPRA = new HashSet<FACTURA_COMPRA>();
            this.PREPARACION = new HashSet<PREPARACION>();
        }
    
        public decimal ID_PRODUCTO { get; set; }
        public decimal STOCK { get; set; }
        public string TIPO_PRODUCTO { get; set; }
        public decimal UNIDAD_MEDIDA_ID_MEDIDA { get; set; }
    
        public virtual ICollection<FACTURA_COMPRA> FACTURA_COMPRA { get; set; }
        public virtual ICollection<PREPARACION> PREPARACION { get; set; }
        public virtual UNIDAD_MEDIDA UNIDAD_MEDIDA { get; set; }
    }
}
