//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public RESERVA()
        {
            this.MESA = new HashSet<MESA>();
        }
    
        public decimal ID_RESERVA { get; set; }
        public decimal HORA { get; set; }
        public System.DateTime FECHA { get; set; }
        public string ESTADO_RESERVA { get; set; }
        public string USUARIO_RUT { get; set; }
        public decimal USUARIO_ROL_ID_ROL { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<MESA> MESA { get; set; }
    }
}
