//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public decimal ID_RESERVA { get; set; }
        public System.DateTime FHORA_LLEGADA { get; set; }
        public System.DateTime FHORA_SALIDA { get; set; }
        public string ESTADO_RESERVA { get; set; }
        public string ACTIVO { get; set; }
        public decimal CLIENTE_ID_CLIENTE { get; set; }
        public decimal MESA_ID_MESA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual MESA MESA { get; set; }
    }
}
