//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.BEBESTIBLE = new HashSet<BEBESTIBLE>();
            this.MESA = new HashSet<MESA>();
            this.PLATO = new HashSet<PLATO>();
        }
    
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_P { get; set; }
        public string APELLIDO_M { get; set; }
        public decimal ROL_ID_ROL { get; set; }
        public string CORREO { get; set; }
        public string DIRECCION { get; set; }
        public string CLAVE { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual ICollection<BEBESTIBLE> BEBESTIBLE { get; set; }
        public virtual ICollection<MESA> MESA { get; set; }
        public virtual ICollection<PLATO> PLATO { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
