using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using CapaNegocio;
using MahApps.Metro.Controls.Dialogs;

namespace Restaurante_Siglo_XXI_DESK
{
    /// <summary>
    /// Lógica de interacción para BoletaInforme.xaml
    /// </summary>
    public partial class BoletaInforme 
    {
        BoletaBN b = new BoletaBN();
        public BoletaInforme()
        {
            InitializeComponent();
            dg_boleta.ItemsSource = b.listarBoleta();
           }

        private void btn_listar_Click(object sender, RoutedEventArgs e)
        {
            DateTime fechaD = Convert.ToDateTime( dp_fecha.SelectedDate);
            
            
            dg_boleta.ItemsSource = b.listaDia(fechaD);

            
        }
        //columnas auto generadas
        private void dg_boleta_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
        

            if (e.Column.Header.Equals("id_boleta") || e.Column.Header.Equals("pedido_id_pedido") || e.Column.Header.Equals("pedido_mesa_id_mesa") || e.Column.Header.Equals("nro_pago"))
            {
                e.Column.Visibility = Visibility.Collapsed;
            }

           //cambiar formato fecha
            if (e.PropertyType == typeof(System.DateTime))
                (e.Column as DataGridTextColumn).Binding.StringFormat = "dd/MM/yyyy";

           


        }

        private void btn_mes_Click(object sender, RoutedEventArgs e)
        {
            DateTime fechaM = Convert.ToDateTime(dp_fecha.SelectedDate);

            dg_boleta.ItemsSource = b.listaMes(fechaM);
            
            int total = 0;


            /*foreach (DataGridColumn column in dg_boleta.Columns)
            {
            if (column.Header.Equals("total_pagar"))
            {

                    MessageBox.Show("" + column.DisplayIndex);
                }
            }*/

            /*for (int i = 0; i < dg_boleta.Items.Count - 1; i++)
            {
                var Id_Producto = (dg_boleta.Items[i]);

            }
  
            */

        }

        

    private async void dg_boleta_AutoGeneratedColumns(object sender, EventArgs e)
    {
        if (dg_boleta.Items.Count.Equals(0))
        {
            await this.ShowMessageAsync("Ups!", "No se encontraron datos");
        }

    }

        private void btn_atras_Click(object sender, RoutedEventArgs e)
        {
            ModuloCaja form = new ModuloCaja();
            form.Show();
            this.Hide();
        }
    }

       
    }

