//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_Siglo_XXI_DESK.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ServicioWeb/", ConfigurationName="ServiceReference1.Servicios")]
    public interface Servicios {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ServicioWeb/Servicios/ListaReservaRequest", ReplyAction="http://ServicioWeb/Servicios/ListaReservaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaReservaWS))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaReserva))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarBoletaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarBoleta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarReservaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarReserva))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaMesaWS))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListDetalle))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaResponse ListaReserva(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServicioWeb/Servicios/ListaReservaRequest", ReplyAction="http://ServicioWeb/Servicios/ListaReservaResponse")]
        System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaResponse> ListaReservaAsync(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ServicioWeb/Servicios/ListaMesaWSRequest", ReplyAction="http://ServicioWeb/Servicios/ListaMesaWSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaReservaWS))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaReserva))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarBoletaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarBoleta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarReservaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarReserva))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaMesaWS))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListDetalle))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaMesaWSResponse ListaMesaWS(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaMesaWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServicioWeb/Servicios/ListaMesaWSRequest", ReplyAction="http://ServicioWeb/Servicios/ListaMesaWSResponse")]
        System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaMesaWSResponse> ListaMesaWSAsync(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaMesaWSRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ServicioWeb/Servicios/AgregarReservaRequest", ReplyAction="http://ServicioWeb/Servicios/AgregarReservaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaReservaWS))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaReserva))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarBoletaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarBoleta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarReservaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarReserva))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaMesaWS))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListDetalle))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarReservaResponse1 AgregarReserva(Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServicioWeb/Servicios/AgregarReservaRequest", ReplyAction="http://ServicioWeb/Servicios/AgregarReservaResponse")]
        System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarReservaResponse1> AgregarReservaAsync(Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarReservaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ServicioWeb/Servicios/ListaReservaWSRequest", ReplyAction="http://ServicioWeb/Servicios/ListaReservaWSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaReservaWS))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaReserva))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarBoletaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarBoleta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarReservaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarReserva))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaMesaWS))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListDetalle))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaWSResponse ListaReservaWS(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServicioWeb/Servicios/ListaReservaWSRequest", ReplyAction="http://ServicioWeb/Servicios/ListaReservaWSResponse")]
        System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaWSResponse> ListaReservaWSAsync(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaWSRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ServicioWeb/Servicios/AgregarBoletaRequest", ReplyAction="http://ServicioWeb/Servicios/AgregarBoletaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaReservaWS))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaReserva))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarBoletaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarBoleta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarReservaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarReserva))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaMesaWS))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListDetalle))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarBoletaResponse1 AgregarBoleta(Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarBoletaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServicioWeb/Servicios/AgregarBoletaRequest", ReplyAction="http://ServicioWeb/Servicios/AgregarBoletaResponse")]
        System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarBoletaResponse1> AgregarBoletaAsync(Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarBoletaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ServicioWeb/Servicios/ListDetalleRequest", ReplyAction="http://ServicioWeb/Servicios/ListDetalleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaReservaWS))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaReserva))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarBoletaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarBoleta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarReservaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarReserva))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListaMesaWS))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListDetalle))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Restaurante_Siglo_XXI_DESK.ServiceReference1.ListDetalleResponse ListDetalle(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServicioWeb/Servicios/ListDetalleRequest", ReplyAction="http://ServicioWeb/Servicios/ListDetalleResponse")]
        System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.ListDetalleResponse> ListDetalleAsync(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListDetalleRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ServicioWeb/")]
    public partial class reserva : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort activoField;
        
        private int clienteidField;
        
        private ushort estadoField;
        
        private int idField;
        
        private System.DateTime fInicioField;
        
        private bool fInicioFieldSpecified;
        
        private System.DateTime fTerminoField;
        
        private bool fTerminoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int clienteid {
            get {
                return this.clienteidField;
            }
            set {
                this.clienteidField = value;
                this.RaisePropertyChanged("clienteid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ushort estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fInicio {
            get {
                return this.fInicioField;
            }
            set {
                this.fInicioField = value;
                this.RaisePropertyChanged("fInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fInicioSpecified {
            get {
                return this.fInicioFieldSpecified;
            }
            set {
                this.fInicioFieldSpecified = value;
                this.RaisePropertyChanged("fInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fTermino {
            get {
                return this.fTerminoField;
            }
            set {
                this.fTerminoField = value;
                this.RaisePropertyChanged("fTermino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fTerminoSpecified {
            get {
                return this.fTerminoFieldSpecified;
            }
            set {
                this.fTerminoFieldSpecified = value;
                this.RaisePropertyChanged("fTerminoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ServicioWeb/")]
    public partial class ListaReservaWS : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ServicioWeb/")]
    public partial class ListaReserva : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ServicioWeb/")]
    public partial class AgregarBoletaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ServicioWeb/")]
    public partial class AgregarBoleta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int totalField;
        
        private int montoPagadoField;
        
        private string fechaField;
        
        private int idPedidoField;
        
        private int idMesaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int MontoPagado {
            get {
                return this.montoPagadoField;
            }
            set {
                this.montoPagadoField = value;
                this.RaisePropertyChanged("MontoPagado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int IdPedido {
            get {
                return this.idPedidoField;
            }
            set {
                this.idPedidoField = value;
                this.RaisePropertyChanged("IdPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int IdMesa {
            get {
                return this.idMesaField;
            }
            set {
                this.idMesaField = value;
                this.RaisePropertyChanged("IdMesa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ServicioWeb/")]
    public partial class AgregarReservaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ServicioWeb/")]
    public partial class AgregarReserva : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string inicioField;
        
        private string terminoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string inicio {
            get {
                return this.inicioField;
            }
            set {
                this.inicioField = value;
                this.RaisePropertyChanged("inicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string termino {
            get {
                return this.terminoField;
            }
            set {
                this.terminoField = value;
                this.RaisePropertyChanged("termino");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ServicioWeb/")]
    public partial class ListaMesaWS : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ServicioWeb/")]
    public partial class ListDetalle : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ServicioWeb/")]
    public partial class mesa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort activoField;
        
        private ushort estadoField;
        
        private int idField;
        
        private int nr_mesaField;
        
        private string usuarioRol_ID_ROLField;
        
        private string usuarioRutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ushort estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int nr_mesa {
            get {
                return this.nr_mesaField;
            }
            set {
                this.nr_mesaField = value;
                this.RaisePropertyChanged("nr_mesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string usuarioRol_ID_ROL {
            get {
                return this.usuarioRol_ID_ROLField;
            }
            set {
                this.usuarioRol_ID_ROLField = value;
                this.RaisePropertyChanged("usuarioRol_ID_ROL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string usuarioRut {
            get {
                return this.usuarioRutField;
            }
            set {
                this.usuarioRutField = value;
                this.RaisePropertyChanged("usuarioRut");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaReserva", WrapperNamespace="http://ServicioWeb/", IsWrapped=true)]
    public partial class ListaReservaRequest {
        
        public ListaReservaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaReservaResponse", WrapperNamespace="http://ServicioWeb/", IsWrapped=true)]
    public partial class ListaReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicioWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Restaurante_Siglo_XXI_DESK.ServiceReference1.reserva[] @return;
        
        public ListaReservaResponse() {
        }
        
        public ListaReservaResponse(Restaurante_Siglo_XXI_DESK.ServiceReference1.reserva[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaMesaWS", WrapperNamespace="http://ServicioWeb/", IsWrapped=true)]
    public partial class ListaMesaWSRequest {
        
        public ListaMesaWSRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaMesaWSResponse", WrapperNamespace="http://ServicioWeb/", IsWrapped=true)]
    public partial class ListaMesaWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicioWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Restaurante_Siglo_XXI_DESK.ServiceReference1.mesa[] @return;
        
        public ListaMesaWSResponse() {
        }
        
        public ListaMesaWSResponse(Restaurante_Siglo_XXI_DESK.ServiceReference1.mesa[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarReserva", WrapperNamespace="http://ServicioWeb/", IsWrapped=true)]
    public partial class AgregarReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicioWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicioWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicioWeb/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string termino;
        
        public AgregarReservaRequest() {
        }
        
        public AgregarReservaRequest(int id, string inicio, string termino) {
            this.id = id;
            this.inicio = inicio;
            this.termino = termino;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarReservaResponse", WrapperNamespace="http://ServicioWeb/", IsWrapped=true)]
    public partial class AgregarReservaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicioWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public AgregarReservaResponse1() {
        }
        
        public AgregarReservaResponse1(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaReservaWS", WrapperNamespace="http://ServicioWeb/", IsWrapped=true)]
    public partial class ListaReservaWSRequest {
        
        public ListaReservaWSRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaReservaWSResponse", WrapperNamespace="http://ServicioWeb/", IsWrapped=true)]
    public partial class ListaReservaWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicioWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Restaurante_Siglo_XXI_DESK.ServiceReference1.reserva[] @return;
        
        public ListaReservaWSResponse() {
        }
        
        public ListaReservaWSResponse(Restaurante_Siglo_XXI_DESK.ServiceReference1.reserva[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarBoleta", WrapperNamespace="http://ServicioWeb/", IsWrapped=true)]
    public partial class AgregarBoletaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicioWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Total;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicioWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MontoPagado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicioWeb/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicioWeb/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int IdPedido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicioWeb/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int IdMesa;
        
        public AgregarBoletaRequest() {
        }
        
        public AgregarBoletaRequest(int Total, int MontoPagado, string Fecha, int IdPedido, int IdMesa) {
            this.Total = Total;
            this.MontoPagado = MontoPagado;
            this.Fecha = Fecha;
            this.IdPedido = IdPedido;
            this.IdMesa = IdMesa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarBoletaResponse", WrapperNamespace="http://ServicioWeb/", IsWrapped=true)]
    public partial class AgregarBoletaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicioWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public AgregarBoletaResponse1() {
        }
        
        public AgregarBoletaResponse1(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListDetalle", WrapperNamespace="http://ServicioWeb/", IsWrapped=true)]
    public partial class ListDetalleRequest {
        
        public ListDetalleRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListDetalleResponse", WrapperNamespace="http://ServicioWeb/", IsWrapped=true)]
    public partial class ListDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ServicioWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] @return;
        
        public ListDetalleResponse() {
        }
        
        public ListDetalleResponse(object[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosChannel : Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosClient : System.ServiceModel.ClientBase<Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios>, Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios {
        
        public ServiciosClient() {
        }
        
        public ServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaResponse Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios.ListaReserva(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaRequest request) {
            return base.Channel.ListaReserva(request);
        }
        
        public Restaurante_Siglo_XXI_DESK.ServiceReference1.reserva[] ListaReserva() {
            Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaRequest inValue = new Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaRequest();
            Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaResponse retVal = ((Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios)(this)).ListaReserva(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaResponse> Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios.ListaReservaAsync(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaRequest request) {
            return base.Channel.ListaReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaResponse> ListaReservaAsync() {
            Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaRequest inValue = new Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaRequest();
            return ((Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios)(this)).ListaReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaMesaWSResponse Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios.ListaMesaWS(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaMesaWSRequest request) {
            return base.Channel.ListaMesaWS(request);
        }
        
        public Restaurante_Siglo_XXI_DESK.ServiceReference1.mesa[] ListaMesaWS() {
            Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaMesaWSRequest inValue = new Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaMesaWSRequest();
            Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaMesaWSResponse retVal = ((Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios)(this)).ListaMesaWS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaMesaWSResponse> Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios.ListaMesaWSAsync(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaMesaWSRequest request) {
            return base.Channel.ListaMesaWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaMesaWSResponse> ListaMesaWSAsync() {
            Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaMesaWSRequest inValue = new Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaMesaWSRequest();
            return ((Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios)(this)).ListaMesaWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarReservaResponse1 Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios.AgregarReserva(Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarReservaRequest request) {
            return base.Channel.AgregarReserva(request);
        }
        
        public string AgregarReserva(int id, string inicio, string termino) {
            Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarReservaRequest inValue = new Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarReservaRequest();
            inValue.id = id;
            inValue.inicio = inicio;
            inValue.termino = termino;
            Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarReservaResponse1 retVal = ((Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios)(this)).AgregarReserva(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarReservaResponse1> Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios.AgregarReservaAsync(Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarReservaRequest request) {
            return base.Channel.AgregarReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarReservaResponse1> AgregarReservaAsync(int id, string inicio, string termino) {
            Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarReservaRequest inValue = new Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarReservaRequest();
            inValue.id = id;
            inValue.inicio = inicio;
            inValue.termino = termino;
            return ((Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios)(this)).AgregarReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaWSResponse Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios.ListaReservaWS(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaWSRequest request) {
            return base.Channel.ListaReservaWS(request);
        }
        
        public Restaurante_Siglo_XXI_DESK.ServiceReference1.reserva[] ListaReservaWS() {
            Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaWSRequest inValue = new Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaWSRequest();
            Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaWSResponse retVal = ((Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios)(this)).ListaReservaWS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaWSResponse> Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios.ListaReservaWSAsync(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaWSRequest request) {
            return base.Channel.ListaReservaWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaWSResponse> ListaReservaWSAsync() {
            Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaWSRequest inValue = new Restaurante_Siglo_XXI_DESK.ServiceReference1.ListaReservaWSRequest();
            return ((Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios)(this)).ListaReservaWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarBoletaResponse1 Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios.AgregarBoleta(Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarBoletaRequest request) {
            return base.Channel.AgregarBoleta(request);
        }
        
        public string AgregarBoleta(int Total, int MontoPagado, string Fecha, int IdPedido, int IdMesa) {
            Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarBoletaRequest inValue = new Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarBoletaRequest();
            inValue.Total = Total;
            inValue.MontoPagado = MontoPagado;
            inValue.Fecha = Fecha;
            inValue.IdPedido = IdPedido;
            inValue.IdMesa = IdMesa;
            Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarBoletaResponse1 retVal = ((Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios)(this)).AgregarBoleta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarBoletaResponse1> Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios.AgregarBoletaAsync(Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarBoletaRequest request) {
            return base.Channel.AgregarBoletaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarBoletaResponse1> AgregarBoletaAsync(int Total, int MontoPagado, string Fecha, int IdPedido, int IdMesa) {
            Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarBoletaRequest inValue = new Restaurante_Siglo_XXI_DESK.ServiceReference1.AgregarBoletaRequest();
            inValue.Total = Total;
            inValue.MontoPagado = MontoPagado;
            inValue.Fecha = Fecha;
            inValue.IdPedido = IdPedido;
            inValue.IdMesa = IdMesa;
            return ((Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios)(this)).AgregarBoletaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Restaurante_Siglo_XXI_DESK.ServiceReference1.ListDetalleResponse Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios.ListDetalle(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListDetalleRequest request) {
            return base.Channel.ListDetalle(request);
        }
        
        public object[] ListDetalle() {
            Restaurante_Siglo_XXI_DESK.ServiceReference1.ListDetalleRequest inValue = new Restaurante_Siglo_XXI_DESK.ServiceReference1.ListDetalleRequest();
            Restaurante_Siglo_XXI_DESK.ServiceReference1.ListDetalleResponse retVal = ((Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios)(this)).ListDetalle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.ListDetalleResponse> Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios.ListDetalleAsync(Restaurante_Siglo_XXI_DESK.ServiceReference1.ListDetalleRequest request) {
            return base.Channel.ListDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Restaurante_Siglo_XXI_DESK.ServiceReference1.ListDetalleResponse> ListDetalleAsync() {
            Restaurante_Siglo_XXI_DESK.ServiceReference1.ListDetalleRequest inValue = new Restaurante_Siglo_XXI_DESK.ServiceReference1.ListDetalleRequest();
            return ((Restaurante_Siglo_XXI_DESK.ServiceReference1.Servicios)(this)).ListDetalleAsync(inValue);
        }
    }
}
